farmlimiter:
  witherskullfarm-disable: true
links:
  discord: 'https://discord.gg/AaguZBXSnr'
  donation: 'https://nocheinf√ºgen.com'
rtp:
  lastteleports: 3
sleepskip:
  mustSleepInPercent: 30
  skipTo: 1000
  skipTime: 70
  stopThunder: true